global:
  scrape_interval: 15s # On récupère les infos toutes les 15 secondes

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker-containers'
    static_configs:
      - targets: ['cadvisor:8080'] # On écoute l'espion cAdvisor